// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD82nhoUmZ0DJWXeecqWzHyDt5QgHDQJRo',
    appId: '1:251642812014:web:734a602cb89c2bca78f87f',
    messagingSenderId: '251642812014',
    projectId: 'instagram-clone-b3a9d',
    authDomain: 'instagram-clone-b3a9d.firebaseapp.com',
    storageBucket: 'instagram-clone-b3a9d.appspot.com',
    measurementId: 'G-0Y13CP4J98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgPZGfp6b44ig8B57C7xsI94yHseKLEI',
    appId: '1:251642812014:android:d11baa375bc71c3878f87f',
    messagingSenderId: '251642812014',
    projectId: 'instagram-clone-b3a9d',
    storageBucket: 'instagram-clone-b3a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBjx80ODi13LbpyF8kSkL7IssmWJQh6WY',
    appId: '1:251642812014:ios:4fe8cc75bfce38fc78f87f',
    messagingSenderId: '251642812014',
    projectId: 'instagram-clone-b3a9d',
    storageBucket: 'instagram-clone-b3a9d.appspot.com',
    iosClientId: '251642812014-o7nar0j8okd2q3a3idnc9cf2mlkk14kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBjx80ODi13LbpyF8kSkL7IssmWJQh6WY',
    appId: '1:251642812014:ios:4fe8cc75bfce38fc78f87f',
    messagingSenderId: '251642812014',
    projectId: 'instagram-clone-b3a9d',
    storageBucket: 'instagram-clone-b3a9d.appspot.com',
    iosClientId: '251642812014-o7nar0j8okd2q3a3idnc9cf2mlkk14kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
